// frontend-react/src/App.tsx
import React from "react";
import { BrowserRouter as Router, Routes, Route } from "react-router-dom";
import { Layout } from "antd";
import SideMenu from "./components/SideMenu";
import DashboardPage from "./pages/DashboardPage";
import CarouselPage from "./pages/CarouselPage";

const App: React.FC = () => {
  return (
    <Router>
      <Layout style={{ minHeight: "100vh" }}>
        <SideMenu />
        <Layout.Content style={{ padding: "20px" }}>
          <Routes>
            <Route path="/" element={<DashboardPage />} />
            <Route path="/carousel" element={<CarouselPage />} />
          </Routes>
        </Layout.Content>
      </Layout>
    </Router>
  );
};

export default App;

// frontend-vue/src/App.vue
<template>
  <a-layout style="min-height: 100vh">
    <SideMenu />
    <a-layout>
      <a-layout-content style="padding: 20px;">
        <router-view />
      </a-layout-content>
    </a-layout>
  </a-layout>
</template>

<script>
import { defineComponent } from 'vue';
import SideMenu from './components/SideMenu.vue';

export default defineComponent({
  name: 'App',
  components: {
    SideMenu,
  },
});
</script>

<style>
</style>
