// frontend-react/src/pages/CarouselPage.tsx
import React from "react";
import { Carousel } from "antd";

const CarouselPage: React.FC = () => {
    return (
        <>
            <h1>Performance Testing Carousel</h1>
            <div style={{ marginLeft: '25%' }}>
                <Carousel autoplay>
                    <div>
                        <img src={`${process.env.PUBLIC_URL}/ice.png`} alt="Ice" />
                    </div>
                    <div>
                        <img src={`${process.env.PUBLIC_URL}/lightning.png`} alt="Lightning" />
                    </div>
                    <div>
                        <img src={`${process.env.PUBLIC_URL}/raindrops.png`} alt="Raindrops" />
                    </div>
                    <div>
                        <img src={`${process.env.PUBLIC_URL}/sunset.png`} alt="Sunset" />
                    </div>
                </Carousel>
            </div>
        </>
    );
};

export default CarouselPage;

// frontend-vue/src/pages/CarouselPage.vue
<template>
  <div>
    <h1>Performance Testing Carousel</h1>
    <div style="margin-left: 25%">
      <a-carousel autoplay>
        <div>
          <img :src="require('@/assets/ice.png')" alt="Ice" />
        </div>
        <div>
          <img :src="require('@/assets/lightning.png')" alt="Lightning" />
        </div>
        <div>
          <img :src="require('@/assets/raindrops.png')" alt="Raindrops" />
        </div>
        <div>
          <img :src="require('@/assets/sunset.png')" alt="Sunset" />
        </div>
      </a-carousel>
    </div>
  </div>
</template>

<script>
import { Carousel } from 'ant-design-vue';

export default {
  name: 'CarouselPage',
  components: {
    ACarousel: Carousel
  }
};
</script>

<style scoped>
</style>
