// frontend-angular/src/app/components/side-menu.component.ts
import { Component } from '@angular/core';

@Component({
  selector: 'app-side-menu',
  templateUrl: './side-menu.component.html',
  styleUrls: ['./side-menu.component.scss']
})
export class SideMenuComponent {
}

<ul nz-menu nzTheme="dark" nzMode="inline">
    <li nz-menu-item routerLink="/">Dashboard</li>
    <li nz-menu-item routerLink="/carousel">Carousel</li>
    <li nz-menu-item routerLink="/lazy">Lazy</li>
    <li nz-menu-item routerLink="/delay">Delayed Form</li>
</ul>

// frontend-react/src/components/SideMenu.tsx
import React from "react";
import { Layout, Menu } from "antd";
import { Link } from "react-router-dom";
import { useState } from "react";

const { Sider } = Layout;

const SideMenu: React.FC = () => {
    const [collapsed, setCollapsed] = useState(false);

    return (
        <Sider collapsible collapsed={collapsed} onCollapse={(value) => setCollapsed(value)}>
            {!collapsed && (
                <Menu theme="dark" mode="inline">
                    <Menu.Item key="1">
                        <Link to="/">Dashboard</Link>
                    </Menu.Item>
                    <Menu.Item key="2">
                        <Link to="/carousel">Carousel</Link>
                    </Menu.Item>
                    <Menu.Item key="3">
                        <Link to="/lazy">Lazy</Link>
                    </Menu.Item>
                    <Menu.Item key="4">
                        <Link to="/delay">Delayed form</Link>
                    </Menu.Item>
                </Menu>
            )}
        </Sider>
    );
};

export default SideMenu;
