// frontend-react/src/pages/Gallery.tsx
import React, { useState } from "react";
import { Upload, Button, Modal, Row, Col, UploadFile, message } from "antd";
import { PlusOutlined, UploadOutlined, DeleteOutlined } from "@ant-design/icons";
import axios from "axios";

const API_URL = "http://localhost:8080/api/gallery";

const GalleryPage: React.FC = () => {
    const [fileList, setFileList] = useState<UploadFile[]>([]);
    const [imageList, setImageList] = useState<{ id: number; filename: string; content: string }[]>([]);
    const [previewImage, setPreviewImage] = useState<string | undefined>(undefined);
    const [previewVisible, setPreviewVisible] = useState<boolean>(false);

    const handleUpload = async () => {
        const formData = new FormData();
        fileList.forEach(file => {
            if (file.originFileObj) {
                formData.append("file", file.originFileObj);
            }
        });

        try {
            await axios.post(`${API_URL}/upload`, formData, {
                headers: { "Content-Type": "multipart/form-data" }
            });
            message.success("Images uploaded successfully");
            setFileList([]);
        } catch (error) {
            console.error("Failed upload:", error);
            message.error("Failed uploading images.");
        }
    };

    const handleFetchImages = async () => {
        try {
            const response = await axios.get<{ id: number; filename: string; content: string }[]>(`${API_URL}/all`);
            setImageList(response.data);
        } catch (error) {
            console.error("Failed fetching images:", error);
            message.error("Failed fetching images.");
        }
    };

    const handlePreview = (file: UploadFile) => {
        if (file.url) {
            setPreviewImage(file.url);
        } else if (file.originFileObj) {
            setPreviewImage(URL.createObjectURL(file.originFileObj));
        }
        setPreviewVisible(true);
    };

    const handleDeleteImage = async (id: number) => {
        try {
            if (id) {
                await axios.delete(`${API_URL}/delete/${id}`);
                message.success("Deleted image.");
                setImageList(prev => prev.filter(img => img.id !== id));
            } else {
                console.error("No id provided for delete operation");
                message.error("Failed deleting image. Invalid ID.");
            }
        } catch (error) {
            console.error("Failed deleting image:", error);
            message.error("Failed deleting image.");
        }
    };


    return (
        <div style={{ padding: 20 }}>
            <Row gutter={16} align="middle" style={{ marginBottom: 20 }}>
                <Col>
                    <Upload
                        listType="picture-card"
                        fileList={fileList}
                        onPreview={handlePreview}
                        onChange={({ fileList }) => setFileList(fileList)}
                        beforeUpload={() => false}
                    >
                        {fileList.length >= 8 ? null : (
                            <div>
                                <PlusOutlined />
                                <div style={{ marginTop: 8 }}>Add image</div>
                            </div>
                        )}
                    </Upload>
                </Col>
                <Col>
                    <Button type="primary" icon={<UploadOutlined />} onClick={handleUpload}>
                        Save images
                    </Button>
                </Col>
                <Col>
                    <Button type="default" onClick={handleFetchImages}>
                        Show all images
                    </Button>
                </Col>
            </Row>
            <Row gutter={[16, 16]}>
                {imageList.map(({ id, filename, content }) => (
                    <Col key={id}>
                        <div style={{ position: "relative" }}>
                            <img
                                src={`data:${content};base64,${content}`}
                                alt={filename}
                                style={{ width: 200, height: 200, objectFit: "cover", borderRadius: 5 }}
                            />
                            <Button
                                type="text"
                                icon={<DeleteOutlined />}
                                danger
                                onClick={() => handleDeleteImage(id)}
                                style={{
                                    position: "absolute",
                                    top: 5,
                                    right: 5,
                                    background: "rgba(255,255,255,0.7)",
                                    borderRadius: "50%"
                                }}
                            />
                        </div>
                    </Col>
                ))}
            </Row>

            <Modal
                open={previewVisible}
                footer={null}
                onCancel={() => setPreviewVisible(false)}
            >
                {previewImage && <img alt="Preview" style={{ width: "100%" }} src={previewImage} />}
            </Modal>
        </div>
    );
};

export default GalleryPage;

// frontend-angular/src/app/pages/gallery/gallery.component.ts
import { Component, OnInit } from '@angular/core';
import { NzMessageService } from 'ng-zorro-antd/message';
import { NzModalService } from 'ng-zorro-antd/modal';
import { HttpClient } from '@angular/common/http';
import { NzUploadFile } from 'ng-zorro-antd/upload';
import { NzUploadChangeParam } from 'ng-zorro-antd/upload';

@Component({
    selector: 'app-gallery',
    templateUrl: './gallery.component.html',
    styleUrls: ['./gallery.component.scss']
})
export class GalleryComponent implements OnInit {
    fileList: NzUploadFile[] = [];
    imageList: { id: number, filename: string, content: string }[] = [];
    previewImage: string | undefined = '';
    previewVisible: boolean = false;
    readonly API_URL = 'http://localhost:8080/api/gallery';

    constructor(
        private http: HttpClient,
        private message: NzMessageService,
        private modal: NzModalService
    ) { }

    ngOnInit(): void {
    }

    handleUpload() {
        const formData = new FormData();
        this.fileList.forEach(file => {
            if (file.originFileObj) {
                formData.append('file', file.originFileObj);
            }
        });

        this.http.post(`${this.API_URL}/upload`, formData, { responseType: 'text' }).subscribe(
            () => {
                this.message.success('Images uploaded successfully');
                this.fileList = [];
            },
            error => {
                console.error('Upload failed:', error);
                this.message.error('Failed uploading images.');
            }
        );
    }

    fetchImages() {
        this.http.get<{ id: number; filename: string; content: string }[]>(`${this.API_URL}/all`).subscribe(
            (response) => {
                this.imageList = response;
            },
            error => {
                console.error('Failed fetching images:', error);
                this.message.error('Failed fetching images.');
            }
        );
    }

    handleDeleteImage(id: number) {
        this.http.delete(`${this.API_URL}/delete/${id}`, { responseType: 'text' }).subscribe(
            () => {
                this.message.success('Deleted image.');
                this.fetchImages();
            },
            error => {
                console.error('Delete failed:', error);
                this.message.error('Failed deleting image.');
            }
        );
    }

    handlePreviewFn = (file: NzUploadFile): void => {
        this.previewImage = file.url || (file.originFileObj ? URL.createObjectURL(file.originFileObj) : '');
        this.previewVisible = true;
    }

    handleCancel() {
        this.previewVisible = false;
    }

    onFileListChange({ fileList }: NzUploadChangeParam): void {
        this.fileList = fileList;
    }

    beforeUpload(file: NzUploadFile): boolean {
        const isImage = file.type?.startsWith('image/');
        if (!isImage) {
            this.message.error('You can only upload image files!');
        }
        return isImage ?? false;
    }

}

<div style="padding: 20px;">
    <nz-row [nzGutter]="16" style="margin-bottom: 20px;">
        <nz-col>
            <nz-upload [nzListType]="'picture-card'" [(nzFileList)]="fileList" [nzPreview]="handlePreviewFn"
                (nzChange)="onFileListChange($event)" [nzBeforeUpload]="beforeUpload">
                <div *ngIf="fileList.length < 8">
                    <i nz-icon nzType="plus"></i>
                    <div style="margin-top: 8px;">Add image</div>
                </div>
            </nz-upload>
        </nz-col>
        <nz-col>
            <button nz-button [nzType]="'primary'" (click)="handleUpload()">
                <i nz-icon nzType="upload"></i> Save images
            </button>
        </nz-col>
        <nz-col>
            <button nz-button (click)="fetchImages()">Show all images</button>
        </nz-col>
    </nz-row>
    <nz-row [nzGutter]="[16, 16]">
        <nz-col *ngFor="let image of imageList">
            <div style="position: relative;">
                <img [src]="'data:image/png;base64,' + image.content" [alt]="image.filename"
                    style="width: 200px; height: 200px; object-fit: cover; border-radius: 5px;" />
                <button nz-button nzType="text" nzDanger (click)="handleDeleteImage(image.id)"
                    style="position: absolute; top: 5px; right: 5px; background: rgba(255,255,255,0.7); border-radius: 50%;">
                    <i nz-icon nzType="delete"></i>
                </button>
            </div>
        </nz-col>
    </nz-row>
    <nz-modal [(nzVisible)]="previewVisible" nzFooter="null" (nzOnCancel)="handleCancel()">
        <img *ngIf="previewImage" [src]="previewImage" alt="Preview" style="width: 100%" />
    </nz-modal>
</div>
