// frontend-react/src/components/SideMenu.tsx
import React from "react";
import { Layout, Menu } from "antd";
import { Link } from "react-router-dom";
import { useState } from "react";

const { Sider } = Layout;

const SideMenu: React.FC = () => {
    const [collapsed, setCollapsed] = useState(false);

    return (
        <Sider collapsible collapsed={collapsed} onCollapse={(value) => setCollapsed(value)}>
            {!collapsed && (
                <Menu theme="dark" mode="inline">
                    <Menu.Item key="1">
                        <Link to="/">Dashboard</Link>
                    </Menu.Item>
                    <Menu.Item key="2">
                        <Link to="/carousel">Carousel</Link>
                    </Menu.Item>
                    <Menu.Item key="3">
                        <Link to="/lazy">Lazy</Link>
                    </Menu.Item>
                    <Menu.Item key="4">
                        <Link to="/delay">Delayed form</Link>
                    </Menu.Item>
                    <Menu.Item key="5">
                        <Link to="/gallery">Gallery</Link>
                    </Menu.Item>
                </Menu>
            )}
        </Sider>
    );
};

export default SideMenu;

// frontend-vue/src/components/SideMenu.vue
<template>
  <a-layout-sider
    :collapsed="collapsed"
    collapsible
    @collapse="onCollapse"
    theme="dark"
  >
    <template v-if="!collapsed">
      <a-menu theme="dark" mode="inline" :selectedKeys="[activeKey]">
        <a-menu-item key="1">
          <router-link to="/">Dashboard</router-link>
        </a-menu-item>
        <a-menu-item key="2">
          <router-link to="/carousel">Carousel</router-link>
        </a-menu-item>
        <a-menu-item key="3">
          <router-link to="/lazy">Lazy</router-link>
        </a-menu-item>
        <a-menu-item key="4">
          <router-link to="/delay">Delayed form</router-link>
        </a-menu-item>
         <a-menu-item key="5">
          <router-link to="/gallery">Gallery</router-link>
        </a-menu-item>
      </a-menu>
    </template>
  </a-layout-sider>
</template>

<script>
import { defineComponent, ref, computed } from 'vue';
import { useRoute } from 'vue-router';

export default defineComponent({
  name: 'SideMenu',
  setup() {
    const collapsed = ref(false);
    const route = useRoute();

    const onCollapse = (value) => {
      collapsed.value = value;
    };

    const activeKey = computed(() => {
      const path = route.path;
      if (path === '/') return '1';
      else if (path === '/carousel') return '2';
      else if (path === '/lazy') return '3';
      else if (path === '/delay') return '4';
      else if (path === '/gallery') return '5';
      return '1';
    });

    return {
      collapsed,
      onCollapse,
      activeKey
    };
  },
});
</script>

<style scoped>
</style>
